### ISSUE TITLE
`Meteor.user()` and `Meteor.userId()` not reactive with Svelte using `useTracker`

### ISSUE THREAD

**Issue by probablykasper** [meteor/simple-todos-svelte#6]
I'm trying to show the user different content based on whether the user is logged in. According to the [Svelte guide](https://www.meteor.com/tutorials/svelte/adding-user-accounts), the following should work for this:
```js
$: currentUser = useTracker(() => Meteor.user());
```

However, when I do this, `currentUser` is just set to an object with a `subscribe` function, and this never changes, even when `Meteor.user()` returns `null` or a user object later on.

Reproduction repo: https://github.com/probablykasper/meteor-usetracker

Meteor 1.12
macOS 10.14.6

Initially submitted [this issue](https://github.com/meteor/meteor/issues/11259) in the meteor repo

**Comment by rdb** [comment]
Yes, you need to use `$currentUser` to access the actual user object, which will work reactively.  This is because useTracker creates a "svelte store".

**Comment by probablykasper** [comment]
@rdb Am I not supposed to use `currentUser` directly?

**Comment by rdb** [comment]
No, use it like you would a Svelte store.

**Comment by probablykasper** [comment]
Got it, my bad then. Thank you
