### ISSUE TITLE
Application structure question

### ISSUE THREAD

**Issue by jamauro** [meteor/simple-todos-svelte#9]
I like the simplicity of this application structure. The one downside I think is wrapping things like publications with an `Meteor.isServer` and I assume you'd need to do the same for tests. From the Meteor docs, it sounds like code wrapped in `Meteor.isServer` will be shipped to the client: https://docs.meteor.com/api/core.html#Meteor-isServer. Have you found this structure to work as your app grows? Any tips on keeping things simple when you have multiple collections, methods, and tests?

**Comment by rdb** [comment]
You can put server-specific imports in a server subdirectory inside the imports directory.

**Comment by jamauro** [comment]
Thanks. I was kind of hoping to avoid subfolders and a bunch of import statements but I think I'm coming around to this structure:

```
imports
- api
-- todos
--- collection.js
--- methods.js
--- publications.js
```

I suppose if [tree-shaking](https://github.com/meteor/meteor/pull/11164) ever gets merged then code in `Meteor.isServer` blocks wouldn't be shipped to the client. That would be really nice.
